/** Major Indian cities → state/UT. Single source for delivery city (Job sheet) and enquiry contact city. */
export const INDIAN_CITY_STATE = {
  Agartala: "Tripura",
  Agra: "Uttar Pradesh",
  Ahmedabad: "Gujarat",
  Aizawl: "Mizoram",
  Ajmer: "Rajasthan",
  Aligarh: "Uttar Pradesh",
  Allahabad: "Uttar Pradesh",
  Amritsar: "Punjab",
  Asansol: "West Bengal",
  Aurangabad: "Maharashtra",
  Bangalore: "Karnataka",
  Bareilly: "Uttar Pradesh",
  Belagavi: "Karnataka",
  Bhopal: "Madhya Pradesh",
  Bhubaneswar: "Odisha",
  Bikaner: "Rajasthan",
  Chandigarh: "Chandigarh",
  Chennai: "Tamil Nadu",
  Coimbatore: "Tamil Nadu",
  Cuttack: "Odisha",
  Dehradun: "Uttarakhand",
  Delhi: "Delhi",
  Dhanbad: "Jharkhand",
  Dibrugarh: "Assam",
  Faridabad: "Haryana",
  Gandhinagar: "Gujarat",
  Gangtok: "Sikkim",
  Ghaziabad: "Uttar Pradesh",
  Goa: "Goa",
  Gorakhpur: "Uttar Pradesh",
  Gurugram: "Haryana",
  Guwahati: "Assam",
  Gwalior: "Madhya Pradesh",
  Hubballi: "Karnataka",
  Hyderabad: "Telangana",
  Imphal: "Manipur",
  Indore: "Madhya Pradesh",
  Itanagar: "Arunachal Pradesh",
  Jabalpur: "Madhya Pradesh",
  Jaipur: "Rajasthan",
  Jalandhar: "Punjab",
  Jammu: "Jammu and Kashmir",
  Jamshedpur: "Jharkhand",
  Jodhpur: "Rajasthan",
  Kanpur: "Uttar Pradesh",
  Kochi: "Kerala",
  Kohima: "Nagaland",
  Kolhapur: "Maharashtra",
  Kolkata: "West Bengal",
  Kota: "Rajasthan",
  Kozhikode: "Kerala",
  Lucknow: "Uttar Pradesh",
  Ludhiana: "Punjab",
  Madurai: "Tamil Nadu",
  Mangalore: "Karnataka",
  Meerut: "Uttar Pradesh",
  Moradabad: "Uttar Pradesh",
  Mumbai: "Maharashtra",
  Mysuru: "Karnataka",
  Nagpur: "Maharashtra",
  Nashik: "Maharashtra",
  "Navi Mumbai": "Maharashtra",
  Noida: "Uttar Pradesh",
  Panaji: "Goa",
  Patna: "Bihar",
  Pondicherry: "Puducherry",
  Pune: "Maharashtra",
  Raipur: "Chhattisgarh",
  Rajkot: "Gujarat",
  Ranchi: "Jharkhand",
  Shillong: "Meghalaya",
  Shimla: "Himachal Pradesh",
  Siliguri: "West Bengal",
  Srinagar: "Jammu and Kashmir",
  Surat: "Gujarat",
  Thane: "Maharashtra",
  Thiruvananthapuram: "Kerala",
  Thrissur: "Kerala",
  Tiruchirappalli: "Tamil Nadu",
  Tirupati: "Andhra Pradesh",
  Udaipur: "Rajasthan",
  Vadodara: "Gujarat",
  Varanasi: "Uttar Pradesh",
  Vijayawada: "Andhra Pradesh",
  Visakhapatnam: "Andhra Pradesh",
  Warangal: "Telangana"
};

/** Major Indian cities for dropdowns (all regions), sorted. */
export const INDIAN_CITIES = Object.keys(INDIAN_CITY_STATE).sort((a, b) =>
  a.localeCompare(b, "en", { sensitivity: "base" })
);

/** State/UT for a city from the list; empty string when unknown. */
export function stateForCity(city) {
  return INDIAN_CITY_STATE[String(city ?? "").trim()] ?? "";
}
